
package com.vpp.staffmanagement;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EmployeeManagementImplementationService", targetNamespace = "http://staffmanagement.vpp.com/", wsdlLocation = "http://localhost:8080/EmployeeManagementImplementationService/employeeManagementWebService?wsdl")
public class EmployeeManagementImplementationService
    extends Service
{

    private final static URL EMPLOYEEMANAGEMENTIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.vpp.staffmanagement.EmployeeManagementImplementationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.vpp.staffmanagement.EmployeeManagementImplementationService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/EmployeeManagementImplementationService/employeeManagementWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/EmployeeManagementImplementationService/employeeManagementWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EMPLOYEEMANAGEMENTIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
    }

    public EmployeeManagementImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeManagementImplementationService() {
        super(EMPLOYEEMANAGEMENTIMPLEMENTATIONSERVICE_WSDL_LOCATION, new QName("http://staffmanagement.vpp.com/", "EmployeeManagementImplementationService"));
    }

    /**
     * 
     * @return
     *     returns EmployeeManagementWebService
     */
    @WebEndpoint(name = "employeeManagementWebServicePort")
    public EmployeeManagementWebService getEmployeeManagementWebServicePort() {
        return super.getPort(new QName("http://staffmanagement.vpp.com/", "employeeManagementWebServicePort"), EmployeeManagementWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeManagementWebService
     */
    @WebEndpoint(name = "employeeManagementWebServicePort")
    public EmployeeManagementWebService getEmployeeManagementWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://staffmanagement.vpp.com/", "employeeManagementWebServicePort"), EmployeeManagementWebService.class, features);
    }

}
