
package com.vpp.staffmanagement;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "SystemUnavailableException", targetNamespace = "http://staffmanagement.vpp.com/")
public class SystemUnavailableException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SystemUnavailableException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SystemUnavailableException_Exception(String message, SystemUnavailableException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SystemUnavailableException_Exception(String message, SystemUnavailableException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.vpp.staffmanagement.SystemUnavailableException
     */
    public SystemUnavailableException getFaultInfo() {
        return faultInfo;
    }

}
